### ISSUE TITLE
No PDB files

### ISSUE THREAD

**Issue by sfinktah** [pmed/v8-nuget#12]
I can't help but notice that the nuget packages you have published do not come with pdb files, nor can I find any reference to such file on the commonly known debug symbol distribution sites for nuget packages.

I have been using `6.8.275.2` (which someone should really update - current release branch is at least `6.8.275.26`.

If there is an older release that includes pdb files, please point me to that, willing to go all the way back to `6.1` to resolve my issue.

**Comment by pmed** [comment]
PDB files are placed in separated packages named like `v8.symbols-$PlatformToolset-$Platform` , e.g. [`v8.symbols-v141-x64`](https://www.nuget.org/packages/v8.symbols-v141-x64/)

**Comment by sfinktah** [comment]
Thanks, you should consider putting that in the README.md.  Any chance of an update of 6.8.275.2 to the latest version?

**Comment by pmed** [comment]
Updated README.md and NuGet packages for V8 version 6.8.275.32
