### ISSUE TITLE
Having issues building 7.0-lkgr

### ISSUE THREAD

**Issue by junhuaw** [pmed/v8-nuget#13]
See //build/config/BUILDCONFIG.gn:570:9: which caused the file to be included.
        [ "//build/config/win:default_cygprofile_instrumentation" ]
          ^------------------------------------------------------
  Traceback (most recent call last):

    File "C:/src/v8-nuget/v8/build/compute_build_timestamp.py", line 120, in <module>

      sys.exit(main())

    File "C:/src/v8-nuget/v8/build/compute_build_timestamp.py", line 104, in main

      last_commit_timestamp = int(open(lastchange_file).read())

  IOError: [Errno 2] No such file or directory: 'C:\\src\\v8-nuget\\v8\\build\\util\\LASTCHANGE.committime'

**Comment by junhuaw** [comment]
Proposed fix: https://github.com/junhuaw/v8-nuget/commit/d084c98cfd06779c1907a6e07909b38374f66b3d?diff=split

**Comment by pmed** [comment]
Hi @junhuaw 

Thank you for the fix!
