### ISSUE TITLE
No-Snapshot and missing blob files related errors

### ISSUE THREAD

**Issue by sigmasoldi3r** [pmed/v8-nuget#15]
Everything works fine at compile time, but there are two scenarios that require some tweaking in the project created:

# No snapshot option

There could be an option/way to disable the snapshot use.

# Snapshot option

If using snapshot (Which is by default), you have to move the working directory of the project, which is the project's one.

Any idea if this can be fixed out of the box without having to modify the solution debug options?

~Regards

**Comment by pmed** [comment]
GN options are placed at the beginning of [`build.py`](https://github.com/pmed/v8-nuget/blob/master/build.py#L35), so you could change them there and build v8 without snapshot.

It's also possible to put the snapshot and native blobs in another place, and to call [v8::InitializeExternalStartupData()](https://v8docs.nodesource.com/node-10.6/df/d43/classv8_1_1_v8.html#a3cd42d90b795ba3664f5189b6e787882) at your program startup.
