### ISSUE TITLE
debug namespaces incomplete

### ISSUE THREAD

**Issue by adenine-dev** [pmed/v8-nuget#17]
When attempting to extend the console of v8 I have found that `v8::debug::ConsoleDelegate` is missing from the header files. However by digging around in the pdb files (`v8.symbols-v142-x64.7.5.288.23\lib\Debug\v8.dll.pdb`), this data does indeed exist, it just isn't in the header. Is there a way to access these classes and functions?

**Comment by pmed** [comment]
Hi,

There is no `v8::debug::ConsoleDelegate` declaration in the public `v8.h` include file available, so I doubt it's possible to use it in your code.

**Comment by adenine-dev** [comment]
I did eventually get it to work, so for anyone in the future that is dealing with this, this is the process I used to fix it.

download the source from [here](https://chromium.googlesource.com/v8/v8/+/refs/heads/master/src), only the src folder is needed.
extract it and link it in to your project where ever you put vendor code in addition to the bundle.
put it in the a src folder because otherwise its includes don't work
you will need to make a bunch of include directories for it to compile, mine include v8/src, and v8
make sure to link it with the nuget package, you may not have to do this, one machine needed it the other didn't.
you do not need to generate `builtins-generated/bytecodes-builtins-list.h`.

I don't know how much of a hack this is but it hasn't thrown up any glaring issues so far so if it ain't broke.
