### ISSUE TITLE
v8 monolith

### ISSUE THREAD

**Issue by epavanello** [pmed/v8-nuget#18]
Is possible to have a monolith version of v8 without dependencies with vcredist? (With runtime /MT)

**Comment by pmed** [comment]
Hi,

Do you mean to build a static `v8.lib` library? You could try to add `v8_static_library = true`,
`is_component_build = false` into `GN_OPTIONS` in the [build.py](https://github.com/pmed/v8-nuget/blob/master/build.py#L35) script.
