### ISSUE TITLE
Git fetch error for protobuf

### ISSUE THREAD

**Issue by raymond-ong** [pmed/v8-nuget#19]
I'm getting this error after running build.py (without any parameter)

> Fetch https://chromium.googlesource.com/external/github.com/google/protobuf@b68a347f56137b4b1a746e8c7438495a6ac1bd91@HEAD into v8/third_party/protobuf
fatal: remote error: Git repository not found
RETRY: v8/third_party/protobuf
Initialized empty Git repository in F:/ISAE/R109/Javascript/v8nuget/v8-nuget/v8/third_party/protobuf/.git/
fatal: remote error: Git repository not found
Traceback (most recent call last):
  File "build.py", line 89, in <module>
    git_fetch(deps[dep], dep)
  File "build.py", line 63, in git_fetch
    subprocess.check_call(fetch_args, cwd=target)
  File "F:\ISAE\R109\Javascript\depot_tools\bootstrap-3_8_0b1_chromium_1_bin\python\bin\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'fetch', '--depth=1', '--update-shallow', '--update-head-ok', '--quiet', 'https://chromium.googlesource.com/external/github.com/google/protobuf@b68a347f56137b4b1a746e8c7438495a6ac1bd91', 'HEAD']' returned non-zero exit status 128

I think the difference is that as of today, inside the DEPS file of v8, protobuf URL is defined as:

>   'v8/third_party/protobuf':
    Var('chromium_url') + '/external/github.com/google/protobuf'+ '@' + 'b68a347f56137b4b1a746e8c7438495a6ac1bd91',

the git_fetch() function inside build.py is splitting the URL by '.git@'
But since there is no ".git" in the DEPS' protobuf URL, the parsing becomes incorrect.

As a workaround, I added special handling for protobuf:
`	# ray: special handling for protobuf`
`	if target != 'v8/third_party/protobuf':`
`		parts = url.split('.git@')`
`	else:`
`		parts = url.split('@')`

Please clarify whether this is my environment problem.
Because after applying the workaround, I still get another error further down the road:
-> This time for fetching android_ndk
KeyError: 'VCINSTALLDIR'
I have Visual C++ 2017 installed. Although I have VS2013 also in this machine.
As a workaround, i temporarily modified this line in build.py
from "14.0" to "15.0"
> vs_version = vs_versions[os.environ.get('VisualStudioVersion', '15.0')]

I also hardcoded my VS path to this:
> vs_install_dir = 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional'
because I don't have "VCINSTALLDIR" Environment variable.

Finally, it proceeded to the Ninja build process. But that too failed 

> ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "build.py", line 167, in <module>
    subprocess.check_call([NINJA, '-C', out_dir, 'v8'], cwd='v8', env=env)
  File "F:\ISAE\R109\Javascript\depot_tools\bootstrap-3_8_0b1_chromium_1_bin\python\bin\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['F:\\ISAE\\R109\\Javascript\\v8nuget\\v8-nuget\\bin\\ninja.exe', '-C', 'out.gn\\lkgr\\v141\\x86\\Debug', 'v8']' returned non-zero exit status 1

For this last error, I saw there are Link Errors above:
` FAILED: bytecode_builtins_list_generator.exe bytecode_builtins_list_generator.exe.pdb`

Followed by ~100 instances of errors like this:

`bytecode-operands.obj : error LNK2001: unresolved external symbol "public: static void __cdecl v8::internal::Internals::CheckInitializedImpl(class v8::Isolate *)" (?CheckInitializedImpl@Internals@internal@v8@@SAXPAVIsolate@3@@Z)`

I currently don't have a workaround or solution to this link error.
I already tried using the VS Developer Command prompt to run build.py.
So I would appreciate any help.

**Comment by tombatron** [comment]
You ever get anywhere with this? I was hoping to build V8 of V8 this morning but uh... No dice.

**Comment by pmed** [comment]
Fetching only required dependencies in v8_v8.1 branch.

**Comment by Vrganj** [comment]
Getting the same issue

**Comment by pmed** [comment]
Hi,

could you be more specific?

**Comment by Vrganj** [comment]
Sorry, I used raymond-ong's workaround and it appears to work now.

**Comment by pmed** [comment]
I have a modified version fo the `build.py` script in v8_8.1 branch. That script fetches only really required to build V8 dependencies, but maybe it works only with Visual C++ 2019. Please note the V8 version 8.2 can be built with Visual C++ 2019.

**Comment by Vrganj** [comment]
I built 8.4 on VS 2019, although, I've got a question about linking the .obj to my project. Do you know how I would do that to create a single DLL output?

**Comment by pmed** [comment]
Hi,

I'm not sure it's possible to build V8 as a single v8.dll

**Comment by pmed** [comment]
Hi @Vrganj 

In fec10f4ed57c48696a8e5d9c0e5858843b190099 I've added a command-line option `--libs=monolith` to the `build.py` script, in order to create a `v8.monolith` NuGet package with the  static library.
