### ISSUE TITLE
Would It Be Possible to Add Support for the XP Variant of the Toolsets?

### ISSUE THREAD

**Issue by 6XGate** [pmed/v8-nuget#2]
I would like to use this package in a project that must support Windows XP.  Since Visual Studio 2012 and up have a different version for XP, it would be nice if these packages worked with that toolset as well.

**Comment by pmed** [comment]
Hi @6XGate, I will try to build V8 for the Windows XP target  in the  near days.

**Comment by pmed** [comment]
@6XGate added XP target support into `build.py` script and links to pre-build packages in README.md

**Comment by 6XGate** [comment]
Cool, I'll check them out, thanks.
