### ISSUE TITLE
non monolith static libraries

### ISSUE THREAD

**Issue by nihalkenkre** [pmed/v8-nuget#20]
hello.

Could you be able to share a args.gn file that would produce static libraries and not be monolithic.

my current args.gn
[args.txt](https://github.com/pmed/v8-nuget/files/5304613/args.txt)

Getting undefined reference errors for the functions.

best regards.
Nihal

**Comment by pmed** [comment]
Hi @amadlover 

I've added the monolithic static build only for some experiment, never tried it with a real program.

As I remember, that non-monolithic build produces a number of v8*.lib libraries, all of them should be linked to the target program.

**Comment by nihalkenkre** [comment]
Yes it creates a bunch of v8* lib files. The total size of the libs are substantially more (dont know exactly how much) than the two dll libs that you provide in the nuget package.

So i am a bit skeptical of linking against them, as there might be a lot of unwanted stuff.

**Comment by pmed** [comment]
Only really used code would be pulled from the static libraries at the link time. In comparison with the dynamic library that always has all the binary code there.

I had no significant differences in the total program size with the static vs. dynamic V8 linking in my project.

**Comment by nihalkenkre** [comment]
> Only really used code would be pulled from the static libraries at the link time. In comparison with the dynamic library that always has all the binary code there.


Great. 

I thought this was the case seeing the size of the embedded build was 10mb with a 163mb monolith lib. 

But did not know for sure. 

Thank you and best regards.
Nihal Kenkre
