### ISSUE TITLE
Not able to build with VS2017/VS2019

### ISSUE THREAD

**Issue by AndreasKhe** [pmed/v8-nuget#21]
Hi,
i'm not able to build using VS2017 or VS2019. I tried with your last provided version vom V8 - but i get build errors:

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\include\type_traits(616): error C2139: "v8::internal::Cell": Eine nicht definierte Klasse ist nicht als Argument fr die systeminterne Typeigenschaft "__is_convertible_to" des Compilers zul„ssig.
D:\data\XXX_FSCCache\Build_v8\_work\v8\out.gn\library_monolithic\gen\torque-generated/internal-class-definitions.h(81): note: Siehe Deklaration von "v8::internal::Cell"
D:\data\XXX_FSCCache\Build_v8\_work\v8\src/codegen/tnode.h(267): note: Siehe Verweis auf die Klasse Vorlage-Instanziierung "std::is_convertible<T,v8::internal::Object>", die kompiliert wird.
        with
        [
            T=v8::internal::Cell
        ]
D:\data\XXX_FSCCache\Build_v8\_work\v8\src/codegen/code-stub-assembler.h(1619): note: Siehe Verweis auf die Klasse Vorlage-Instanziierung "v8::internal::is_subtype<v8::internal::Cell,v8::internal::Cell>", die kompiliert wird.
D:\data\XXX_FSCCache\Build_v8\_work\v8\src/objects/objects.h(275): note: Siehe Verweis auf die Klasse Vorlage-Instanziierung "v8::internal::TaggedImpl<v8::internal::HeapObjectReferenceType::STRONG,v8::internal::Address>", die kompiliert wird.
`

Any idea/help what is wrong in my environment?

**Comment by pmed** [comment]
Hi,

As I remember, recent V8 versions can be built only with Visual C++ 2019.

It seems you are using Visual C++ 2017 (i.e. version 14.16.27023)



пн, 30 нояб. 2020 г., 14:53 Andreas Beil <notifications@github.com>:

**Comment by AndreasKhe** [comment]
Hello,
thank you - doing it explictly with VS2019 seems to work fine.
But the contained files 'appveyor-build.bat' + 'vswhere_usability_wrapper.cmd' seem to be forseen for VS2017. Therefore i tried it.

**Comment by pmed** [comment]
I tried to build the latest V8 version 8.9, and the build was not successful. It seems the V8 dependencies in the DEPS file have no `v8` prefix now. 

That `appveyor-build.bat` was an attempt to build V8 on the Appveyour CI. It probably wouldn't work now due to the build was time limits.

**Comment by AndreasKhe** [comment]
VS2017 build seems to work fine.

What about 'natives_blob.bin' + 'snapshot_blob.bin' - they seem to be missing now!?

**Comment by pmed** [comment]
As I remember, the V8 blobs should be embedded into the library by default. You could try to add  an explicit `--gn-option v8_use_external_startup_data=true` GN option to the build.py  command-line. 

There are other possible `build.py` options available on `build.py --help` output.

**Comment by AndreasKhe** [comment]
I tried following parameters:
`--gn-option show_includes=False`

Which ends up (on gn level) like this:
`show_includes="false"` (WITH quotes)

As a result the flag '`show_includes`' is **not** recognized.

I did not manage to provide the parameter in a way that it ends up correctly (without quotes).

Any suggestion?

**Comment by pmed** [comment]
Hi @AndreasKhe,

Thanks for sharing! I've improved the  `--gn-option` values parsing as bools for  `True/yes/on` and `False/no/off`. Please try the latest master.
