### ISSUE TITLE
Installing in Visual Studio 2017

### ISSUE THREAD

**Issue by oliverbock** [pmed/v8-nuget#5]
I have installed v8-v140-x64 (v5.9.211.28) into Visual Studio 2017 using the in-built NuGet Package Manager.  The doco says "All necessary files (*.lib, *.dll, *.pdb) should be referenced in the project automatically with MsBuild property sheets.", but I had to add the Additional Include Directories, Additional Library Directories and Linker Additional Dependencies manually.

I can see that the .props files exist, and there are no errors in the Package Manager Output window.

When I ask for detailed logging of the build, the only reference to .props files is:
> Task "Error" skipped, due to false condition; (!Exists('packages\v8.redist-v140-x64.5.9.211.28\build\native\v8.redist-v140-x64.props')) was evaluated as (!Exists('packages\v8.redist-v140-x64.5.9.211.28\build\native\v8.redist-v140-x64.props')).
> Task "Error" skipped, due to false condition; (!Exists('packages\v8-v140-x64.5.9.211.28\build\native\v8-v140-x64.props')) was evaluated as (!Exists('packages\v8-v140-x64.5.9.211.28\build\native\v8-v140-x64.props')).

which I don't know whether is positive or negative.

Did I do something wrong, or does it not work with Visual Studio 2017?

**Comment by pmed** [comment]
Toolset version `v140` is for Visual Studio 2015, please try to install package for Visual Studio 2017 toolset `v141` named  `v8-v141-x64 5.9.211.28`

I will update that README file for the Visual Studio 2017 support.

**Comment by oliverbock** [comment]
Works perfectly.  Thanks.
