### ISSUE TITLE
Does not work with vs2017 on version 6.7-lkgr

### ISSUE THREAD

**Issue by junhuaw** [pmed/v8-nuget#8]
Assuming depot_tools is a prerequisite (not mentioned in README.md - installed separately), the build process does not work out of the box.   These are the known missing things:

set VisualStudioVersion=15.0
#need to set vc install dir
...

Also can you upload the pdb files to nuget?

**Comment by pmed** [comment]
There is no need in `depot_tools` to build the V8 with `build.py` script. Theis script shall be invoked in a Visual Studio Developer command, i.e. with python.exe, cl.exe, and link.exe accessible.

See also comments in #7 

...
PDB files are placed in packages `v8.symbols*`: https://www.nuget.org/packages?q=v8.symbols 
DLL files are placed in packages `v8.redist*`: https://www.nuget.org/packages?q=v8.redist

**Comment by junhuaw** [comment]
Thanks @pmed .  Running from VS command prompt helped.  I can build latest lkgr version with vs2017 correctly.  6.7-lkgr hit some linking issue - probably real issue than your build script.

I have VS2017 15.7.2, Windows SDK 10.0.17134.0
